name: Build and Release Android Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: '11'

      - name: Download libv2ray
        run: cd V2rayNG/app/libs && wget https://github.com/retiredmate/AndroidLibXrayLite/releases/download/1687379760/libv2ray.aar

      - name: Update permissions for gradlew
        run: chmod +x V2rayNG/gradlew

      - name: Build Android project
        run: cd V2rayNG && ./gradlew assembleRelease

      - name: Generate unique ID
        id: generate_id
        run: echo "::set-output name=unique_id::$(date +%s)"
        
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate_id.outputs.unique_id }}
          release_name: Release ${{ steps.generate_id.outputs.unique_id }}
          draft: false
          prerelease: false

      - name: Upload APK to arm64 release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: V2rayNG/app/build/outputs/apk/release/v2rayNG_1.8.5_arm64-v8a.apk
          asset_name: v2rayNG_1.8.5_arm64-v8a.apk
          asset_content_type: application/vnd.android.package-archive
          
      - name: Upload APK to armeabi-v7a release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: V2rayNG/app/build/outputs/apk/release/v2rayNG_1.8.5_armeabi-v7a.apk
          asset_name: v2rayNG_1.8.5_armeabi-v7a
          asset_content_type: application/vnd.android.package-archive
          
      - name: Upload APK to fat release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: V2rayNG/app/build/outputs/apk/release/v2rayNG_1.8.5_null.apk
          asset_name: v2rayNG_1.8.5_null.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload APK to x86 release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: V2rayNG/app/build/outputs/apk/release/v2rayNG_1.8.5_x86.apk
          asset_name: v2rayNG_1.8.5_x86.apk
          asset_content_type: application/vnd.android.package-archive
          
      - name: Upload APK to x86_64 release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: V2rayNG/app/build/outputs/apk/release/v2rayNG_1.8.5_x86_64.apk
          asset_name: v2rayNG_1.8.5_x86_64.apk
          asset_content_type: application/vnd.android.package-archive
